version: '3.9'

services:
  web:
    build: .
    environment:
      PORT: 8000
      HOST: 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: > 
            bash -c "python manage.py wait_for_db &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000" 

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
