# Generated by Django 5.0 on 2023-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_movie_booking_event_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug_title',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
